---
- name: Updated apt repo and packages cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Perform a dist-upgrade
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: Check if a reboot is required.
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: false
  register: reboot_required_file

- name: Reboot the server (if required)
  ansible.builtin.reboot:
    msg: "Rebooting the server after apllying Kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists

- name: Remove dependencies that are no longer required.
  ansible.builtin.apt:
    autoremove: true
